
name: Scrape & Post
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium
      - name: Run scraper
        run: |
          mkdir -p out
          python -m scraper.run --limit 500 || true
      - name: Ensure and preview output
        run: |
          mkdir -p out data
          touch out/snapshot.jsonl out/snapshot.csv
          echo "---- JSONL size / head ----"
          ls -l out/snapshot.jsonl || true
          wc -l out/snapshot.jsonl || true
          head -n 10 out/snapshot.jsonl || true
          echo "---- CSV size / head ----"
          ls -l out/snapshot.csv || true
          wc -l out/snapshot.csv || true
          head -n 10 out/snapshot.csv || true
      - name: Commit snapshot to repo
        run: |
          set -e
          mkdir -p data
          cp out/snapshot.jsonl data/snapshot.jsonl || true
          cp out/snapshot.csv data/snapshot.csv || true
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/snapshot.jsonl data/snapshot.csv || true
          git commit -m "chore(data): update snapshot [skip ci]" || echo "Nothing to commit"
          git push origin HEAD:${{ github.ref_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapshot
          path: |
            out/snapshot.jsonl
            out/snapshot.csv
          if-no-files-found: warn
